trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: npmjs-sample-variables

resources:
  repositories:   
  - repository: templates
    type: git
    name: Operações/template-take-blip
    ref: refs/tags/v1.3
    
extends:
  template: template-pipeline.yml@templates    
  parameters:    
    packagename: blip-services
    type: javascript
    to: semantic-release
    npmCmds:
    - npm cache clean -f
    - npm i -g npm@^2.0.0
    - npm prune
    - npm install
    - npm run build
